### ISSUE TITLE
Demo store

### ISSUE THREAD

**Issue by magicpriest** [moovweb/react-storefront#2]
It's not an issue though, but it would be really convenient if documentation has not only examples, but an real demo-store.
After quick dig in documentation everything look really pretty, so I would use it in next day for sure.

Real life example: 
There is library [React-admin](https://github.com/marmelab/react-admin) by marmelab, and the first thing in readme is demos, that attract small companies and unskilled developers for try out reactive approach of creating apps.

**Comment by markbrocato** [comment]
Indeed.  We're actually working on that next sprint.  Stay tuned.  For now, when you create a new app with create-react-storefront, it gives you a pretty full-fledged demo.  We'll be building that out further and hosting it in the near future.

**Comment by markbrocato** [comment]
We've published an example store based on generated placeholder data that demonstrates how to build a typical shopping flow with react-storefront:

https://react-storefront-boilerplate.moovdemos.com/

The code for the site can be found here: https://github.com/moovweb/react-storefront-boilerplate

You can create your own copy of the site using create-react-storefront:

```
npm install -g create-react-storefront
create-react-storefront my-site
```
