### ISSUE TITLE
Updating RSF v6.54.0 creates issues with redirects on pages with CMS slots

### ISSUE THREAD

**Issue by Kassares** [moovweb/react-storefront#336]
Project - Annieselke
Example page - `/contact`
Getting infinite redirect and load to same page on RSF starting from v6.54.0

**Comment by markbrocato** [comment]
@dijs This is fairly urgent. Please take a look next week.

**Comment by dijs** [comment]
@markbrocato I will check it out today

**Comment by dijs** [comment]
@markbrocato I found the culprit PR https://github.com/moovweb/react-storefront/pull/266

Not sure where the exact problem code is yet

**Comment by dijs** [comment]
Interesting, after trying to remove most of the changes from that PR, the bug still existed.

Although, after checking out master and reverting that PR's changes, everything works as expected. So I may need some help finding the actual buggy code.
