### ISSUE TITLE
Question: Licence variant

### ISSUE THREAD

**Issue by lfurzewaddock** [moovweb/react-storefront#67]
Interesting project. Which licence have you opened sourced your codebase under? MIT, BSD, GPL?

**Comment by markbrocato** [comment]
We have not formally chosen a license yet, but we are leaning towards Apache or MIT.  It will be very permissive and definitely not GPL.

**Comment by lfurzewaddock** [comment]
Thanks @markbrocato

**Comment by brokenthorn** [comment]
Honestly. This project is really cool! Probably the only small and light (not a lot of deps) e-commerce project out there. Please hurry up! :D

**Comment by markbrocato** [comment]
@brokenthorn We've updated the license to Apache-2.0!  It's now properly open-sourced. 🎉
