### ISSUE TITLE
not  able to build cause of maybe yarn version 1.13.0 

### ISSUE THREAD

**Issue by raitalharehman** [moovweb/react-storefront#72]
when i run  : yarn link:all
it show log like this
yarn run v1.13.0
$ yarn build; cd packages/react-storefront/dist; npm link; yarn link; cd ../../../; cd packages/babel-plugin-react-storefront; npm link; yarn link; cd ../../; cd packages/react-storefront-moov-xdn/dist; npm link; yarn link; cd ../../../;
error Command "build;" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by raitalharehman** [comment]
i was trying on windows, working fine on Linux 
but unable to find a way to deploy and run server 
can we deploy it other then moovweb xdn  ?

**Comment by raitalharehman** [comment]
got it 
https://stackoverflow.com/questions/54454790/can-react-storefront-pwa-of-moovweb-deploy-other-then-moovweb-xdn

**Comment by dijs** [comment]
Here is the guide for deploying with express https://pwa.moovweb.com/guides/express
